# Site settings
title: 0x8Layer
description: "0x8Layer CTF Team"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: 0x8Layer
user_title: 0x8Layer
twitter_username: 0x8Layer
github_username: 0x8Layer
profile_picture:  https://avatars1.githubusercontent.com/u/66396987?s=400&u=35a44de78ec213dde5bb8195f12765cb4884dada&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
# Build settings
# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/0x8layer
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/0x8layer
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: writeups
    url: https://github.com/0x8LayerTeam/CTF-Writeups

# exclude my node related stuff
exclude: ["package.json", "src", "node_modules"]
